Mirror account
platanus/ledgerizer pull request #43
Opened 2020-09-06 01:11 UTC by ldlsegovia

Funcionalidad de cuentas espejo con multicurrency

#### Cuentas espejo

Opcionalmente en entries que trabajan con cuentas multicurrency se puede especificar un `conversion_amount`. Al hacer esto, si corremos el siguiente código:

```ruby
class DepositCreator
  include Ledgerizer::Execution::Dsl

  def perform
    execute_user_deposit_entry(tenant: Portfolio.new, document: UserDeposit.first, datetime: "1984-06-04", conversion_amount: Money.from_amount(600, 'CLP')) do
      debit(account: :bank, accountable: Bank.first, amount: Money.from_amount(10, 'USD'))
      credit(account: :funds_to_invest, accountable: User.first, amount: Money.from_amount(10, 'USD'))
    end
  end
end
```

obtendermos 2 entries. La primera contendrá líneas por los 10 USD (monto original) y la segunda por su equivalente en la moneda del tenant (CLP). En este caso, dos líneas de 6000 CLP que es el resultado de multiplicar 10 USD x 600 CLP (valor de conversión).
> Cabe destacar que además se generarán cuentas especiales para llevar el balance de estos montos convertidos.

2020-09-06 01:16 UTC, ldlsegovia commented
![](https://github.trello.services/images/mini-trello-icon.png) [2. Modificar ledgerizer para que pueda crear cuentas espejo](https://trello.com/c/guXiEc6M/658-2-modificar-ledgerizer-para-que-pueda-crear-cuentas-espejo)

2020-09-07 18:35 UTC, difernandez requested changes
Buena, gran cambio! Dejo un par de comentarios/dudas, principalmente detalles de tests

2020-09-07 18:35 UTC, difernandez commented on spec/dummy/spec/lib/execution/entry_spec.rb
> +  context "with conversion_amount" do
Faltó el "invalid" en la descripción

2020-09-07 18:35 UTC, difernandez commented on spec/dummy/spec/lib/execution/entry_spec.rb
> +      let(:expected_accounts) do
Quizás se puede definir esto un nivel más arriba para compartirlo con el context "with no conversion amount", redefiniendo solo `conversion_amount`, `conversion_amount` y `mirror_currency`

2020-09-07 18:35 UTC, difernandez commented on spec/dummy/spec/lib/execution/dsl_spec.rb
> +          credit(data[:credit])
de donde sale el `data`?

2020-09-07 18:35 UTC, difernandez commented on app/models/ledgerizer/account.rb
> +        :account_mirror_currency, :amount_currency
Creo que no entendí bien lo de los filtros, se está agregando la posibilidad de filtrar por el mirror? y si es así, por que se agrega a `forbidden_line_filters`?

2020-09-07 18:35 UTC, difernandez commented on README.md
> +obtendermos 2 entries. La primera contendrá líneas por los 10 USD (monto original) y la segunda por su equivalente en la moneda del tenant (CLP). En este caso, dos líneas de 6000 CLP que es el result
*obtendremos

2020-09-07 18:37 UTC, ldlsegovia commented on db/migrate/20190828180322_create_ledgerizer_accounts.rb
> -        :account_type,
Sí, está bien porque una cuenta es única por tenant, nombre, accountable, currency y mirror_currency. Es redundante el  tipo

2020-09-07 18:40 UTC, ldlsegovia commented on app/models/ledgerizer/account.rb
> +        :account_mirror_currency, :amount_currency
está en `forbidden_line_filters` porque no tiene sentido filtrar desde una cuenta por `account_mirror_currency`. La cuenta tiene un único `mirror_currency`

2020-09-07 18:43 UTC, ldlsegovia commented on spec/dummy/spec/lib/execution/dsl_spec.rb
> +          credit(data[:credit])
De acá https://github.com/platanus/ledgerizer/blob/master/spec/dummy/spec/support/test_class_helpers.rb#L13 quizás hay una forma más linda de pasar esa data externa pero bueno, funciona.

2020-09-07 18:44 UTC, ldlsegovia commented on spec/dummy/spec/lib/definition/entry_spec.rb
> +      before { search_params[:account_currency] = "CLP" }
ah, yeah me equivoqué.

2020-09-07 18:45 UTC, ldlsegovia commented on app/models/ledgerizer/entry.rb
> +    end
buen ojo

2020-09-10 18:46 UTC, ldlsegovia commented on spec/dummy/spec/lib/execution/entry_executor_spec.rb
> -  describe "#initialize" do
porque es probar de nuevo `Ledgerizer::Execution::Entry.new` y la verdad se usa indirectamente en todos los otros tests. Entonces en vez de seguir duplicando con lo nuevo pensé en dejarlo concentrado en `Ledgerizer::Execution::Entry`

2020-09-11 12:46 UTC, difernandez requested changes

2020-09-11 12:46 UTC, difernandez commented on spec/dummy/spec/lib/definition/tenant_spec.rb
> +  fdescribe "#add_account" do
Se pasó una "f" en el `describe`

2020-09-11 12:54 UTC, difernandez approved these changes

2020-09-15 20:08 UTC, merged